### ISSUE TITLE
Octomap comparison. 

### ISSUE THREAD

**Issue by Caveats** [ethz-asl/voxgraph#28]
Hello! This looks phenomenal. I'd love the chance to discuss your work! 
We're looking at a very similar use case - based on Octrees / Octomap - which leads into a sanitised display via Unity. 

I've got an SD card on it's way (no PI just a Nano) so really interested to see what tracking is resolved. I've got some indoor localised RealSense 435i footage of flat navigation - using the depth cam + IMU. 

I'd be interested to see how the two maps play out? We're also thinking a lot about the cooperative mapping aspect. The mapping we're probably going to start with something handheld? Can you see any issues with this. Since on the tin (as it were) this seems like a really good approach? 

Is there any data / computational overhead versus an Octree? Could an Octree - in theory be rendered out in VoxGraph?

**Comment by victorreijgwart** [comment]
Hi Caveats,
Glad to hear that you're interested in this code :)
The answer to your question about octrees is that it depends. Voxgraph uses [voxblox](https://github.com/ethz-asl/voxblox) as its mapping framework, which instead of octrees uses a hashmap of blocks (each block typically contains 16x16x16 voxels). These hashmaps are usually computationally more lightweight in terms of updates and random queries. Octrees would typically be more efficient in terms of data. Depending on the implementation, they can be fast when querying points that are near to each other in space and they offer a nice way to model the world at multiple resolutions.
Regarding the Nano, do you mean a Jetson Nano? Volumetric mapping is very expensive, so we usually use Intel NUCs as our minimal setup. But we have run voxgraph on a Jetson TX2 and although this is close to its limits, it worked. The computational cost varies strongly with the voxel resolution, so if you're having trouble to run it, it's worth trying it with larger voxels.
What do you mean by 'Could an octree be rendered out in voxgraph'? Updating voxgraph to internally use octrees instead of hash maps is possible, but it would take quite a lot of work.  Converting octrees to hash maps for data loading, or converting hash maps to octrees for visualization should be easier.

**Comment by Caveats** [comment]
Very impressive and thank you for the details.

We're looking at Octomaps (and have found that approx 30cm+ squares is a good place to target)
Our EP1 uses Ultrasonics and MM Wave to range and detect. Whilst Volumetric is expensive when we knock this down to something closer to a "experience map" - as opposed to be it being scanned and referred to for navigation. 

Our solution doesn't need the navigations aspect - only the mapping? I know that in CompSci courses the mapping methods you use are the next steps. 

We also use some sneaky hashmaps but further down in our rendering pipeline. 
I did mean the Nano - I was intrigued to see what you could squeeze out of it - but the TX2 would give you more power.

**Comment by victorreijgwart** [comment]
Hi Caveats, that's great to hear!
If you have any more questions, please don't hesitate to ask. In the meantime, can I close this issue?
