### ISSUE TITLE
Voxgraph RVIZ plugin

### ISSUE THREAD

**Issue by hridaybavle** [ethz-asl/voxgraph#31]
Hi, 

Great job with the voxgraph, amazing work!! I am trying to use Voxgraph for mapping using RBGD cameras. I am able to output and visualize the /**combined_mesh** in rviz but not the /**submap_surface_pointclouds** as the msg is of voxgraph. I see in your [video](https://www.youtube.com/watch?v=N9p1_Fkxxro&feature=youtu.be) you are able visualize the RGB pointcloud map. 

Could you tell me how to setup the /**submap_surface_pointclouds** so that I could visualize the 3D RGB pointcloud map as in Voxblox?

**Comment by victorreijgwart** [comment]
Hi!

Sorry for the late reply. The `/submap_surface_pointclouds` only contain the mesh vertices.
For visualization we usually use the `/combined_mesh` or `/separated_mesh` topics. What you're looking for is probably the `/combined_mesh` colored by RGB value, instead of by normals (default). You can change it [here in the code](https://github.com/ethz-asl/voxgraph/blob/1289be1d260f18b0f89b1dfa959ec60b9d8e775b/voxgraph/src/tools/visualization/submap_visuals.cpp#L86) by replacing `voxblox::ColorMode::kNormals` with `voxblox::ColorMode::kColor`.

Please let me know if this works for you. Then I'll add this as an option that is configurable over ROS params.

**Comment by hridaybavle** [comment]
Thanks for the reply, I will try it as you mention :) For now I will close this issue.

**Comment by liuzhenboo** [comment]
good!
