### ISSUE TITLE
voxgraph_mapper node dies if tsdf size is 0.05 

### ISSUE THREAD

**Issue by SchmiederX** [ethz-asl/voxgraph#54]
As I figured out my problem in #52  I have some follow up questions. 

The PC we run voxgraph on is an 8 core i7 with 24GB of RAM. And our Dataset consists of street scenes similar to the Kitti Dataset.  
 
If we run voxgraph with a tsdf size of 0.05 on our Dataset the map has a lot of holes. And the voxgraph_mapping node shuts itself down after some time.

![sparse_map](https://user-images.githubusercontent.com/33832215/107010081-2d6ff780-6796-11eb-9956-7edc10847d4e.png)

![voxgraph_died](https://user-images.githubusercontent.com/33832215/107011360-d1a66e00-6797-11eb-87af-97dcffc40b1b.png)

The submap creation interval is 1 second and the frequence of the velodyne is 10Hz.
Is there any way to avoid this or is 0.05 m voxel size just too small for such a large scene?

**Comment by alexmillane** [comment]
This is very small voxel size for this size of scene. I suspect the holes are because your computer is unable to process pointclouds fast enough and the shutdown is because you run out of memory. You also have to consider your rays are touching surfaces very sparsely at their extremes, which will also cause holes.

The problem is that in the standard mode of operation, voxblox (which is performing volumetric integration for voxgraph) is densely allocating observed space along each ray.

Let's say you have your ray length set to 20m, and you approximately observe a rectangular prism 40m x 40m x 10m high. The number of voxels in this volume is large:

`(40m x 40m x 10m) / (0.05m x 0.05m x 0.05m) = 128million voxels.`

assume 2 floats per voxel (ignoring the color which is currently stored no matter what):

`128000000 / 8bytes ~ 1Gb`

So ~1Gb from a single observation and ~100million voxel updates. There's your problem.

Now other TSDF frameworks avoid this problem by not allocating space along the whole ray, only immediately around surfaces. Voxblox can actually do this by altering the parameters: `voxel_carving_enabled` and `voxel_carving_enabled`, see: https://github.com/ethz-asl/voxblox-plusplus/issues/12

I'm not sure how well this mode is tested though honestly, because the library was sort of envisioned for path-planning where you need freespace information and large voxels are ok (in large environments).

**Comment by SchmiederX** [comment]
hey @alexmillane, 

thank you for your very fast and accurate answer! The problem with the holes as you describe seems very plausible to me, as at 7cm voxel size its still working but as I lower the size to 5cm it seems that the rays at greater distances just dont 'touch' enough voxes anymore. 

I will look into the `voxel_carving_enabled` and the `allow_clear` parameters. Im running a test right now and it seems that the memory usage goes down by about half, which is great!

We will use it for planning aswell but we have a lot of slow driving scenarios and we try to get a lot of details like poles and other small obstacles into the map.

**Comment by alexmillane** [comment]
Hi @SchmiederX.

No worries :). I hope that you can find some settings that work for you.

Good luck with it.

Cheers,
Alex

**Comment by ynma-hanvo** [comment]
@alexmillane  as what  you said,  voxgraph/voxgraph is the wrong tool for building fidelity surface,  do you have any suggestion for that. thanks a lot.

**Comment by victorreijgwart** [comment]
@ynma-hanvo, what type of dataset are you working with? Is it LiDAR or depth camera-based? Are you reconstructing individual objects, indoor scenes, or outdoor scenes?

**Comment by ynma-hanvo** [comment]
> @ynma-hanvo, what type of dataset are you working with? Is it LiDAR or depth camera-based? Are you reconstructing individual objects, indoor scenes, or outdoor scenes?
hi, victorreijgwart, thanks for you reply. my main focus is for depth camera-based  indoor scenes (up to 100m radius scene).

**Comment by victorreijgwart** [comment]
Hi @ynma-hanvo,
Sorry for the slow response. I was out of office for most of the past month.
Have you considered using RTAB-Map? I haven't used it recently, but I remember it working well and it supports RGB-D inputs. In case it does not include a sufficiently good mesh generation feature for your use case, it might be worth using RTAB-Map to estimate the poses of all the depth images in your dataset and then run them through voxblox or NVblox to generate a high-quality mesh.

**Comment by ynma-hanvo** [comment]
> Hi @ynma-hanvo, Sorry for the slow response. I was out of office for most of the past month. Have you considered using RTAB-Map? I haven't used it recently, but I remember it working well and it supports RGB-D inputs. In case it does not include a sufficiently good mesh generation feature for your use case, it might be worth using RTAB-Map to estimate the poses of all the depth images in your dataset and then run them through voxblox or NVblox to generate a high-quality mesh.

I tried voxgraph and it works quite well if    vio drift is small.  I will try RTAB-Map, really appropriated for  your suggestion.

**Comment by victorreijgwart** [comment]
For datasets with more odometry drift, RTAB-Map might help as it incorporates loop closures. Either way, I'm glad to hear voxgraph already works quite well!
