### ISSUE TITLE
about registration_method  

### ISSUE THREAD

**Issue by ynma-hanvo** [ethz-asl/voxgraph#77]
hi, this is a great project which can make global mapping more accurate despite the vio drift.  
 I found  the registration constraint is really important,   there is two methods  "implicit_to_implicit" and "explicit_to_implicit",  can you describe  about the two different methods,   and suggestion for getting better result.

**Comment by victorreijgwart** [comment]
Hi @ynma-hanvo, thank you for your question. I would recommend to only use the `explicit_to_implicit` method.
When aligning a submap A to a submap B, the difference between the two methods is that `explicit_to_implicit` aligns the surface points of A to the ESDF of B, whereas `implicit_to_implicit` aligns the ESDF voxels of A to the ESDF of B.
We mainly included the `implicit_to_implicit` method for verification purposes. In our tests, considering all the ESDF voxels of A instead of only the surface points did not provide meaningful accuracy improvements, despite being much slower. This intuitively makes sense since there are many more voxels than surface points, while the information that's useful for registration is mainly concentrated on the surface.
